### ISSUE TITLE
bug: Error on opening nvim in Windows and Flickering Explorer

### ISSUE THREAD

**Issue by sahilsk** [folke/snacks.nvim#1308]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.4

### Operating system/version

Windows 11

### Describe the bug

I am seeing error on opening nvim . Though it doens't affect anything as ignore it but still would be great if could be figure out how to resolve it?

I use `powershell 7.5`

```lua
Error executing vim.schedule lua callback: 
...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: Invalid 'window': Expected Lua number
stack traceback:
[C]: in function 'nvim_win_call'
...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: in function 'render'
...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:282: in function '_move'
...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:162: in function 'view'
...im-data/lazy/snacks.nvim/lua/snacks/explorer/actions.lua:17: in function 'reveal'
...im-data/lazy/snacks.nvim/lua/snacks/explorer/actions.lua:61: in function 'fn'
vim/_editor.lua:351: in function <vim/_editor.lua:350>

```

Second issue is with explorer. First the curson flicks and then it goes up/down on its own as if controlled by a ghost.
On opening the explorer PREVIEW the window kept refreshing. This is the error i see in the notification

```lua
Error executing vim.schedule lua callback: vim/shared.lua:235: t: expected table, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua:936: in function 'validate'
vim/shared.lua:234: in function 'tbl_values'
...-data/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:412: in function 'update_titles'
...-data/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:854: in function 'find'
...a/lazy/snacks.nvim/lua/snacks/picker/source/explorer.lua:222: in function <...a/lazy/snacks.nvim/lua/snacks/picker/source/explorer.lua:217>

```
Recording of this can be found [here](https://drive.google.com/file/d/107beeM1kt4kfpqI68H0su5H9ypwvWEpp/view?usp=sharing)

My explorer config

```
      explorer = {
        -- keymap: https://github.com/folke/snacks.nvim/blob/main/lua/snacks/picker/config/sources.lua#L80-L107
        enabled = true,
        replace_netrw = true,
        layout = {
          preset = "sidebar",
          preview = true
        },
        follow_file = true,
        tree = true,
        focus="list",
        formatters = {
          file = { filename_only = true },
          severity = { pos = "right" },
        },

      },

``

### Steps To Reproduce

It happened when i installed snacks from scratch in neovim in windows.

```
NVIM v0.10.4
Build type: Release
LuaJIT 2.1.1713484068
```


### Expected Behavior

Should show no error

### Repro

```lua
...
```

**Comment by dpetka2001** [comment]
Did you try using Wezterm on Windows? Also your config is wrong. Read the [explorer docs](https://github.com/folke/snacks.nvim/blob/main/docs/explorer.md) please. You're juggling together the explorer options and the explorer picker options.

**Comment by folke** [comment]
It seems that the explorer is getting refreshed continuously.

This can only happen if one or more files are constantly changing in the dirs you have open (can be invisible),
or if you have an LSP that constantly sends diagnostics updates.

Another user had `git.fsmonitor` enabled in their `gitconfig`, not sure if this is related, but it might be.

**Comment by sahilsk** [comment]
I am trying ot debug this..  Nothing is working in nvim after installing snacks ecosystem. I had lsp working before and now it's not. sorry for this spam, i've not done this before

**Comment by folke** [comment]
Can you set `opts.picker.sources.explorer.watch = false` and see if that fixes it?

**Comment by folke** [comment]
Might have been related to https://github.com/folke/snacks.nvim/issues/1321.
I added a work-around for that in the meantime.
Can you update and check?

**Comment by folke** [comment]
In your video, how did you open Neovim?
It seems the explorer tried to open, but then a file opened instead.
Are you using an auto-session plugin and opened Neovim with `nvim .`?

**Comment by folke** [comment]
You are probably doing exactly that. I can at least reproduce it with `persistence.nvim`, adding the below to `init.lua`:

```lua
vim.api.nvim_create_autocmd("UIEnter", {
  nested = true,
  callback = function(ev)
    vim.cmd("silent %bw!")
    vim.cmd("silent clearjumps")
    require("persistence").load()
  end,
})
```

That's pretty much what auto-session plugins do.

**Comment by sahilsk** [comment]
Yes, you are right i'm doing `nvim .` only
When i simply directly open the file `nvim xyz.txt` or simpley dashboard `nvim ` i don't face this weird error

```
Error executing vim.schedule lua callback: ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: Invalid 'window': Expected Lua number                   stack traceback:                                                                          [C]: in function 'nvim_win_call'                                                  ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: in function 'render'                                                                               ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:282: in function '_move'                                                                                ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:162: in function 'view'                                                                                 ...im-data/lazy/snacks.nvim/lua/snacks/explorer/actions.lua:17: in function 'update'                                                                                ...a/lazy/snacks.nvim/lua/snacks/picker/source/explorer.lua:111: in function 'fn'                                                                                   vim/_editor.lua:351: in function <vim/_editor.lua:350>    
```

**Comment by folke** [comment]
did you update and see if you can still reproduce those issues?

**Comment by folke** [comment]
Also, why are you doing `nvim .` and not just `nvim`. 
I don't get why people do that.

**Comment by sahilsk** [comment]
oh wiat... issue is not closed yet. sorry

i'm still getting the error

```

Error executing vim.schedule lua callback: ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: Invalid 'window': Expected Lua number                   stack traceback:                                                                          [C]: in function 'nvim_win_call'                                                  ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:572: in function 'render'                                                                               ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:282: in function '_move'                                                                                ...im-data/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:162: in function 'view'                                                                                 ...im-data/lazy/snacks.nvim/lua/snacks/explorer/actions.lua:17: in function 'update'                                                                                ...a/lazy/snacks.nvim/lua/snacks/picker/source/explorer.lua:111: in function 'fn'                                                                                   vim/_editor.lua:351: in function <vim/_editor.lua:350>   

```


I've removed autosession plugin and replaced by persistence
```
  -- Save and load buffers (a session) automatically for each folder
  -- MUST NOT USE AS IT'S INCOMPATIBLE WITH SNACKS
  --  {
  --    'rmagatti/auto-session',
  --    config = function()
  --      require("auto-session").setup {
  --        log_level = "error",
  --        auto_session_suppress_dirs = { "~/", "~/Downloads" },
  --      }
  --    end
  --  },

  {
    "folke/persistence.nvim",
    event = "BufReadPre", -- this will only start session saving when an actual file was opened
    opts = {
      -- #  ~/AppData/Local/nvim-data
      dir = vim.fn.stdpath("state") .. "/sessions/", -- directory where session files are saved
      -- minimum number of file buffers that need to be open to save
      -- Set to 0 to always save
      need = 1,
      branch = true, -- use git branch to save session
    }
  },
```
And this is my snacks config

```
return {
  {
    "folke/snacks.nvim",
    priority = 2000,
    lazy = false,
    ---@type snacks.Config
    opts = {
      image = {enabled = false},
      bigfile = { enabled = true },
      -- just for which-key doc styling
      toggle = {
        enabled = true,
        map = vim.keymap.set, -- keymap.set function to use
        which_key = true, -- integrate with which-key to show enabled/disabled icons and colors
        notify = true, -- show a notification when toggling
        -- icons for enabled/disabled states
        icon = {
          enabled = " ",
          disabled = " ",
        },
        -- colors for enabled/disabled states
        color = {
          enabled = "green",
          disabled = "yellow",
        },
        wk_desc = {
          enabled = "Disable ",
          disabled = "Enable ",
        },
      },

      dashboard = { 
        enabled = true,
        sections = {
          { section = "header" },
          { section = "keys", gap = 1, padding = 1 },
          {
            section = "terminal",
            cmd = "ascii-image-converter C:\\Users\\Kumar\\Documents\\SocialMediaChannels\\ChannelResources\\firefly-kakashi-ninja-v1-xs.png -C -c",
            random = 10,
            pane = 2,
            indent = 4,
            height = 25,
          },
          { pane = 2, icon = " ", title = "Recent Files", section = "recent_files", indent = 2, padding = 1 },
          { pane = 2, icon = " ", title = "Projects", section = "projects", indent = 2, padding = 1 },
          {
            pane = 2,
            icon = " ",
            title = "Git Status",
            section = "terminal",
            enabled = function()
              return Snacks.git.get_root() ~= nil
            end,
            cmd = "git status --short --branch --renames",
            height = 5,
            padding = 1,
            -- ttl = 5 * 60,
            indent = 3,
          },
          { section = "startup" },
        },


      }, -- dashboard
      terminal = {
        enabled = true,
        win = { style = "terminal" },
        shell ="pwsh.exe",
        opts = {
          layout = {
            preset = "ivy",
            preview = true
          },

        }
      },
      explorer = {
        -- keymap: https://github.com/folke/snacks.nvim/blob/main/lua/snacks/picker/config/sources.lua#L80-L107
        enabled = true,
        replace_netrw = true,

      },
      indent = { enabled = true },
      input = { enabled = true },
      notifier = {
        enabled = true,
        timeout = 3000,
      },
      picker = {
        enabled = true,
        hidden=true ,
        sources= {
          explorer = {
            watch = false,
            layout = {
              preset = "sidebar",
              preview = true
            },
            follow_file = true,
            tree = true,
            focus="list",
            formatters = {
              file = { filename_only = true },
              severity = { pos = "right" },
            },
          },
        }
      },

      quickfile = { enabled = true },

      scope = { enabled = true },

      scroll = { enabled = true },

      statuscolumn = { enabled = true },

      words = { enabled = true },

      styles = {
        notification = {
          wo = { wrap = true } -- Wrap notifications
        }
      }

    },
    keys = {
      -- Top Pickers & Explorer
      { "<leader><space>", function() Snacks.picker.smart() end, desc = "Smart Find Files" },
      { "<leader>,", function() Snacks.picker.buffers() end, desc = "Buffers" },
      -- { "<leader>/", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader>:", function() Snacks.picker.command_history() end, desc = "Command History" },
      { "<leader>nn", function() Snacks.picker.notifications() end, desc = "Notification History" },
      { "<leader>e", function() Snacks.explorer() end, desc = "File Explorer" },
      -- find
      { "<leader>bb", function() Snacks.picker.buffers() end, desc = "Buffers" },
      { "<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find Config File" },
      { "<leader>ff", function() Snacks.picker.files() end, desc = "Find Files" },
      { "<leader>fg", function() Snacks.picker.git_files() end, desc = "Find Git Files" },
      { "<leader>fp", function() Snacks.picker.projects() end, desc = "Projects" },
      { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent" },
      -- git
      { "<leader>gb", function() Snacks.picker.git_branches() end, desc = "Git Branches" },
      { "<leader>gl", function() Snacks.picker.git_log() end, desc = "Git Log" },
      { "<leader>gL", function() Snacks.picker.git_log_line() end, desc = "Git Log Line" },
      { "<leader>gs", function() Snacks.picker.git_status() end, desc = "Git Status" },
      { "<leader>gS", function() Snacks.picker.git_stash() end, desc = "Git Stash" },
      { "<leader>gd", function() Snacks.picker.git_diff() end, desc = "Git Diff (Hunks)" },
      { "<leader>gf", function() Snacks.picker.git_log_file() end, desc = "Git Log File" },
      -- Grep
      { "<leader>sb", function() Snacks.picker.lines() end, desc = "Buffer Lines" },
      { "<leader>sB", function() Snacks.picker.grep_buffers() end, desc = "Grep Open Buffers" },
      { "<leader>sg", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader>sw", function() Snacks.picker.grep_word() end, desc = "Visual selection or word", mode = { "n", "x" } },
      -- search
      { '<leader>s"', function() Snacks.picker.registers() end, desc = "Registers" },
      { '<leader>s/', function() Snacks.picker.search_history() end, desc = "Search History" },
      { "<leader>sa", function() Snacks.picker.autocmds() end, desc = "Autocmds" },
      { "<leader>sb", function() Snacks.picker.lines() end, desc = "Buffer Lines" },
      { "<leader>sc", function() Snacks.picker.command_history() end, desc = "Command History" },
      { "<leader>sC", function() Snacks.picker.commands() end, desc = "Commands" },
      { "<leader>sd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
      { "<leader>sD", function() Snacks.picker.diagnostics_buffer() end, desc = "Buffer Diagnostics" },
      { "<leader>sh", function() Snacks.picker.help() end, desc = "Help Pages" },
      { "<leader>sH", function() Snacks.picker.highlights() end, desc = "Highlights" },
      { "<leader>si", function() Snacks.picker.icons() end, desc = "Icons" },
      { "<leader>sj", function() Snacks.picker.jumps() end, desc = "Jumps" },
      { "<leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
      { "<leader>sl", function() Snacks.picker.loclist() end, desc = "Location List" },
      { "<leader>sm", function() Snacks.picker.marks() end, desc = "Marks" },
      { "<leader>sM", function() Snacks.picker.man() end, desc = "Man Pages" },
      { "<leader>sp", function() Snacks.picker.lazy() end, desc = "Search for Plugin Spec" },
      { "<leader>sq", function() Snacks.picker.qflist() end, desc = "Quickfix List" },
      { "<leader>sR", function() Snacks.picker.resume() end, desc = "Resume" },
      { "<leader>su", function() Snacks.picker.undo() end, desc = "Undo History" },
      { "<leader>uC", function() Snacks.picker.colorschemes({layout = "ivy"}) end, desc = "Colorschemes" },
      -- LSP
      { "gd", function() Snacks.picker.lsp_definitions() end, desc = "Goto Definition" },
      { "gD", function() Snacks.picker.lsp_declarations() end, desc = "Goto Declaration" },
      { "gr", function() Snacks.picker.lsp_references() end, nowait = true, desc = "References" },
      { "gI", function() Snacks.picker.lsp_implementations() end, desc = "Goto Implementation" },
      { "gy", function() Snacks.picker.lsp_type_definitions() end, desc = "Goto T[y]pe Definition" },
      { "<leader>ss", function() Snacks.picker.lsp_symbols() end, desc = "LSP Symbols" },
      { "<leader>sS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "LSP Workspace Symbols" },
      -- Other
      { "<leader>z",  function() Snacks.zen() end, desc = "Toggle Zen Mode" },
      { "<leader>Z",  function() Snacks.zen.zoom() end, desc = "Toggle Zoom" },
      { "<leader>.",  function() Snacks.scratch() end, desc = "Toggle Scratch Buffer" },
      { "<leader>S",  function() Snacks.scratch.select() end, desc = "Select Scratch Buffer" },
      { "<leader>n",  function() Snacks.notifier.show_history() end, desc = "Notification History" },
      { "<leader>bd", function() Snacks.bufdelete() end, desc = "Delete Buffer" },
      { "<leader>cR", function() Snacks.rename.rename_file() end, desc = "Rename File" },
      { "<leader>gB", function() Snacks.gitbrowse() end, desc = "Git Browse", mode = { "n", "v" } },
      { "<leader>gg", function() Snacks.lazygit() end, desc = "Lazygit" },
      { "<leader>un", function() Snacks.notifier.hide() end, desc = "Dismiss All Notifications" },
      { "<c-/>",      function() Snacks.terminal() end, desc = "Toggle Terminal" },
      { "<c-_>",      function() Snacks.terminal() end, desc = "which_key_ignore" },
      { "]]",         function() Snacks.words.jump(vim.v.count1) end, desc = "Next Reference", mode = { "n", "t" } },
      { "[[",         function() Snacks.words.jump(-vim.v.count1) end, desc = "Prev Reference", mode = { "n", "t" } },
      {
        "<leader>N",
        desc = "Neovim News",
        function()
          Snacks.win({
            file = vim.api.nvim_get_runtime_file("doc/news.txt", false)[1],
            width = 0.6,
            height = 0.6,
            wo = {
              spell = false,
              wrap = false,
              signcolumn = "yes",
              statuscolumn = " ",
              conceallevel = 3,
            },
          })
        end,
      }
    },
    init = function()
      vim.api.nvim_create_autocmd("User", {
        pattern = "VeryLazy",
        callback = function()
          -- Setup some globals for debugging (lazy-loaded)
          _G.dd = function(...)
            Snacks.debug.inspect(...)
          end
          _G.bt = function()
            Snacks.debug.backtrace()
          end
          vim.print = _G.dd -- Override print to use snacks for `:=` command

          -- Create some toggle mappings
          Snacks.toggle.option("spell", { name = "Spelling" }):map("<leader>us")
          Snacks.toggle.option("wrap", { name = "Wrap" }):map("<leader>uw")
          Snacks.toggle.option("relativenumber", { name = "Relative Number" }):map("<leader>uL")
          Snacks.toggle.diagnostics():map("<leader>ud")
          Snacks.toggle.line_number():map("<leader>ul")
          Snacks.toggle.option("conceallevel", { off = 0, on = vim.o.conceallevel > 0 and vim.o.conceallevel or 2 }):map("<leader>uc")
          Snacks.toggle.treesitter():map("<leader>uT")
          Snacks.toggle.option("background", { off = "light", on = "dark", name = "Dark Background" }):map("<leader>ub")
          Snacks.toggle.inlay_hints():map("<leader>uh")
          Snacks.toggle.indent():map("<leader>ug")
          Snacks.toggle.dim():map("<leader>uD")
        end,
      })
    end,
  },



  {
    "folke/todo-comments.nvim",
    optional = true,
    keys = {
      { "<leader>st", function() Snacks.picker.todo_comments() end, desc = "Todo" },
      { "<leader>sT", function () Snacks.picker.todo_comments({ keywords = { "TODO", "FIX", "FIXME" } }) end, desc = "Todo/Fix/Fixme" },
    },
  },



  {
    "folke/trouble.nvim", 
    opts = {
      modes = {
        test = {
          mode = "diagnostics",
          preview = {
            type = "split",
            relative = "win",
            position = "right",
            size = 0.3,
          },
        },
      },
    }, -- for default options, refer to the configuration section for custom setup.
    cmd = "Trouble",
    keys = {
      {
        "<leader>xx",
        "<cmd>Trouble diagnostics toggle<cr>",
        desc = "Diagnostics (Trouble)",
      },
      {
        "<leader>xX",
        "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
        desc = "Buffer Diagnostics (Trouble)",
      },
      {
        "<leader>cs",
        "<cmd>Trouble symbols toggle focus=false<cr>",
        desc = "Symbols (Trouble)",
      },
      {
        "<leader>cl",
        "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
        desc = "LSP Definitions / references / ... (Trouble)",
      },
      {
        "<leader>xL",
        "<cmd>Trouble loclist toggle<cr>",
        desc = "Location List (Trouble)",
      },
      {
        "<leader>xQ",
        "<cmd>Trouble qflist toggle<cr>",
        desc = "Quickfix List (Trouble)",
      },
    },
  }



}

```

**Comment by sahilsk** [comment]
> Also, why are you doing `nvim .` and not just `nvim`. I don't get why people do that.

`nvim .`  loads all the files in the current directory while nvim require one extra step after loading.  productivtiy productivity productivity 💃

**Comment by folke** [comment]
1. so first of all you did not update snacks, looking at that trace.
2. please of please only post proper traces here and not one big jumbled line. I fixed the ones in the issue description, but I'm not going to keep doing this
3. I never said auto-session is incompatible with snacks.
4. you do `nvim .` which tells Neovim to open the directory. Not the files in it, but a buffer displaying the directory contents. Normally using netrw, but when the snacks picker is enabled, snacsk will open the explorer.
5. you automatically load a session after opening neovim, which clears all open windows and buffers
6. that is what gave the initial error.  since dnacks explorer opens, auto session kills it and explorer tries to update
7. `nvim . ` does **NOT** load all files in the current directory. You clearly don't understand how Neovim works. Maybe you habe a plugin that does that, but NEovim does not do that.

So again, please update and test again.

IF the problem persists, and you see a stacktrace, provide me with a proper stacktrace.

**Comment by JohnWilliston** [comment]
I think there's still something to this. I am using the latest update of Snacks (commit 07f4b9a), I am _not_ opening Neovim with `nvim .` only my usual `nvim`, and I'm still seeing the flashing in _some_ folders when I open the snacks explorer. The picker part of my snacks config is as follows for reference:

```language-lua
        picker = {
            enabled = true,
            explorer = {
                watch = false,
            },
        },
```

Interestingly enough, I find I can make the problem happen in any folder as long as I close all buffers except the open snacks explorer (without configuring it to close when it's the last thing open of course). Maybe that helps somehow?

**Comment by luccpaiva** [comment]
I suspect I'm having the same problem, and only for a bigger window. If the window is bigger than a given limit, it flickers.

Setting `watch = false` helps, but this is a useful thing to have turned on.

https://github.com/user-attachments/assets/d9390445-bdab-42c3-9f2e-ec47b3ceae30

**Comment by JohnWilliston** [comment]
FWIW, I haven't had this problem with it for a while. But then the latest versions of Snacks, Edgy, Noice, etc. have all fixed I think every single problem I've had before with them. I feel like I've reached Neovim bliss now :)
