### ISSUE TITLE
bug: image is not rendered over ssh

### ISSUE THREAD

**Issue by jiz4oh** [folke/snacks.nvim#1785]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0

### Operating system/version

Macos 13.6.6

### Describe the bug

The image shows properly if I am using Kitty w/o ssh 

![Image](https://github.com/user-attachments/assets/8bf91c3b-669a-49d2-b651-915d7cb98a29)

but don't show when I am using Kitty w/ ssh

![Image](https://github.com/user-attachments/assets/67803c57-6cff-4da3-891a-866b804fa950)

### Steps To Reproduce

1. open the image in kitty w/ ssh
2. connect ssh `ssh localhost`
3. open the image in kitty

### Expected Behavior

render image over ssh

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
      image = {},
    } },
    -- add any other plugins here
  },
})
```

**Comment by jiz4oh** [comment]
not stale

**Comment by karamanliev** [comment]
Doesn't work for me too, with or without tmux. Tried everything from #1156.
- set `SNACKS_KITTY` env var
- got latest magic installed on both client (arch linux) and host (macos).
- have termgui colors set

![Image](https://github.com/user-attachments/assets/1d7b0155-05c6-43b1-9c1f-1ef8789c5a37)

**Comment by stevenxxiu** [comment]
I got it mostly working in *Tmux*. The issues I encountered:

- Using nested *Tmux* doesn't work, as *snacks* *image* doesn't run the *Tmux* escape sequence twice. Patching this requires knowing how deep we're nested.
- *Tmux* actually caps the maximum escape sequence lengths. See <https://github.com/tmux/tmux/issues/4161#issuecomment-2450847965> on how to patch this.

**Comment by stevenxxiu** [comment]
It'll be appreciated if you could just upvote the previous comment, if there's nothing to add. This reduces email traffic.

**Comment by Mayur1009** [comment]
I was able to get it working by setting the `SSH_CLIENT` or `SSH_CONNECTION` env variables.

**Comment by karamanliev** [comment]
I have all of these defined in my shell but still unable to view images in SSH inside or outside of tmux. I used the minimal configuration provided for debugging with no additional plugins installed.

<img width="812" height="211" alt="Image" src="https://github.com/user-attachments/assets/1e330f53-859c-4567-8be7-49a53fa92847" />

My use case is ssh-ing from linux (Arch) computer to a macbook pro laptop.

**Comment by stevenxxiu** [comment]
I think I've fixed the issue in *Ghostty*. Try out my fix #2082 and see if it works in your cases.

Some issues to be aware of that I encountered while fixing this, that this PR doesn't address:

- Using nested *Tmux* doesn't work. This requires using the *Tmux* escape sequence $n$ times if we're nested inside $n$ instances of *Tmux*. *snacks* *image* doesn't do this. Patching this requires knowing how deeply we're nested.
- *Tmux* actually caps the maximum escape sequence length. Images with big file sizes won't work. See <https://github.com/orgs/tmux/discussions/4225> for a patch to increase the limit.

**Comment by karamanliev** [comment]
I'm using kitty.

I tested your branch with the minimal config, but unfortunately the problem still exists. Images just don't show up in a ssh session (without tmux). `image.nvim` works, `yazi` also works fine in a ssh session, even inside tmux.

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "stevenxxiu/snacks.nvim",
      branch = "fix/image-terminal-request",
      opts = {},
    },
  },
})
```

**Comment by stevenxxiu** [comment]
@karamanliev I tried running *Kitty* to SSH into an *Arch Linux* server and it works fine. I just have *Ghostty* terminfo, but this shouldn't be an issue, as images work for you in other places. It works both inside and outside of *Tmux*.

    $ TERM=xterm-ghostty ssh bharani

The minimal config:

```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
  local out = vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { 'Failed to clone lazy.nvim:\n', 'ErrorMsg' },
      { out, 'WarningMsg' },
      { '\nPress any key to exit...' },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  spec = {
    'stevenxxiu/snacks.nvim',
    branch = 'fix/image-terminal-request',
    lazy = false,
    ---@type snacks.Config
    opts = {
      image = {
        enabled = true,
        force = true, -- Required in SSH *Tmux*
      },
    },
    config = true,
    priority = 1000,
  },
})
```

    $ /usr/bin/nvim --clean -u init.lua

**Comment by karamanliev** [comment]
Maybe it's related because I'm ssh-ing from a Linux machine to a MacOS machine. Neovim is installed from brew, maybe it's that?

Edit: Just tried the other way around - ssh from the MacOS laptop into the Linux machine and images are working in and out of tmux!

**Comment by jiz4oh** [comment]
not stable, please reopen this issue

**Comment by blurgyy** [comment]
Not stale

**Comment by jiz4oh** [comment]
Hi @folke, could you please take a look at this? It's still a bug
