### ISSUE TITLE
feature: add motions to snacks indent 

### ISSUE THREAD

**Issue by pBorak** [folke/snacks.nvim#231]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Ability to jump to the top/bottom of the indent.

### Describe the solution you'd like

In https://github.com/echasnovski/mini.indentscope, there are mappings that allow users to navigate to the top and bottom of the indent, as well as text objects within the scope. It would be great to have this functionality in Snacks as well.

### Describe alternatives you've considered

-

**Comment by folke** [comment]
I'm not sure this should be part of snacks.
I'm using this indent text object for `mini.ai`: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/mini.lua#L10

It's used here: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/coding.lua#L163-L163

**Comment by folke** [comment]
I'll think about it

**Comment by pBorak** [comment]
That works for me. Feel free to close this. Thanks for another great plugin!

**Comment by folke** [comment]
the one from mini.ai I think?

**Comment by dpetka2001** [comment]
Yeah, you can set `custom_textobjects.i = false` to disable it. When doing `dai` the `LazyVim.mini.ai_indent` leaves an empty line behind. I prefer the `mini.indentscope` behavior, which deletes it as a block leaving no empty line behind.

**Comment by folke** [comment]
Both text objects and jumping has been added to the `scope` plugin.

Please refer to the updated docs for more info: https://github.com/folke/snacks.nvim/blob/main/docs/scope.md

You need to `enable` the `scope` plugin to automatically have the keymaps created.
Alternatively, you can create them manually.

Every text-object or jump can be fully configured to make it behave like you want.

The defaults are roughly based on similar functionality in indentscope.

So `]i`, `[i`, `ii`, `ai`.

Let me know what you think!

**Comment by swarn** [comment]
Is there a typo where the object is defined on `ia` instead of `ai`?

**Comment by folke** [comment]
Yes indeed 😅
I was using manual keymaps all the time and only tested a couple of keymaps when I added the automatic creation.

Just fixed it.

**Comment by pBorak** [comment]
Hmm, something seems off with the `ii` text object when Treesitter is enabled. It does not select 'inside' the scope; instead, it selects the entire scope. Essentially, there is no difference between `ai` and `ii`.
```
      scope = {
        enabled = true,
        keys = {
          textobject = {
            ii = {
              edge = false,
              treesitter = { enabled = true },
            },
            ai = {
              edge = true,
              treesitter = { enabled = true },
            },
          },
        },
      },
```

https://github.com/user-attachments/assets/b6e76cea-076f-40a4-92bb-9e86af2fa090

Let me know if you need more detailed steps.

**Comment by dpetka2001** [comment]
I'm facing another weird behavior. I have the following in my personal config
```lua
      scope = {
        keys = {
          textobject = {
            ai = {
              linewise = true,
            },
            ii = {
              linewise = true,
            },
          },
        },
      },
```
If I put the cursor on key `ai` and press `dii` it will delete everything inside `textobject`. Buf if I press `dai` it will delete just the `ai` object. I would expect that when pressing `dii` will only delete the line `linewise = true`, but instead it deletes everything inside the `textobject` key.

If I put a comment in the `ai` key like so
```lua
  ai = {
    -- test
    linewise = true,
  },
```
then pressing `dii` correctly deletes the 2 lines inside the `ai` key. It seems that when there's only one line in the inside scope it doesn't calculate it correctly?? Or did I miss any option that I should pass into my configuration?

**Comment by folke** [comment]
`min_size=2` is the default for scopes, which means I always try to expand the scope to be at least two lines.
Just changed the default for text objects and jumps.

I had also made it so that if you select a bunch of lines, you can then use the indent text objects that cover all the lines, but I didn't properly deal with inner scopes. If you're on an edge, the inner scope was properly found, but then expanded to include the current line, which of course is incorrect.

Please update and let me know if you seen anything else weird.

Also be aware that there's a lot of ways to configure the algorithm, like min_size, max_size, etc

**Comment by folke** [comment]
Also, both for jumps and textobjects, snacks will expand to the scope parent if the current visual selection matches the intended scope. So you can keep doing `ii`, `ai` to further expand the scopes.

**Comment by folke** [comment]
Important to note as well is that the `linewise` option, when not specifically set, will automatically use linewise or blockwise based on `v` or `V` visual mode.

**Comment by dpetka2001** [comment]
Yes, I see. I should have followed the types trail `TextObject -> Opts -> Config` to see what other options I could put into the textobject. Sorry about that.

**Comment by kiyoon** [comment]
In python, it always select one more line below than expected.

**Comment by folke** [comment]
@kiyoon just updated to prefer the lower block when on the edge of two blocks.

**Comment by kiyoon** [comment]
@folke Thank you. But the problem still exists.

```python
if a:
    pass
else:   # <- cursor
    pass

b = 1
```

`vai` selects the bottom line.

**Comment by folke** [comment]
I just pushed a bunch of changes related to text objects.
The defaults have been changed and now use treesitter if available, since that's a more accurate method.
With treesitter, selecting full and inner scopes now even works when you would remove all formatting in the code.

So @pBorak your issue should be fixed. You also don't need to change any settings to make it work.

@kiyoon same for you. Although, doing `vii` in your second example, will select lines 2-4, based on the TS parse...

`min_size` should also be left at `2`. Making it lower will result in single line scopes, which is probably never what you want.

**Comment by kiyoon** [comment]
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/36bd587b-b02e-4a8f-9729-f295a86e3686" />

Now it seems like the indent module is broken?

**Comment by folke** [comment]
Are you sure you're using the latest version?

**Comment by kiyoon** [comment]
<img width="546" alt="image" src="https://github.com/user-attachments/assets/4d89a5be-f973-4a5a-b787-1e769ca4d04e" />

Yes I just updated it

**Comment by kiyoon** [comment]
https://github.com/user-attachments/assets/3c487ece-efac-4157-87b2-9c572246fd13

Now there is a UI bug in my setup for some reason, and the textobject still selects two if statements.

**Comment by folke** [comment]
@kiyoon would you mind sharing part of that file? It has something to do with using tabs for indentation.
I have some changes locally that probably fix that, that I still need to push.
Having some code to test would be useful.

**Comment by kiyoon** [comment]
It happens for basically all python files it seems.

But the file was this one: https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/aa.py

**Comment by folke** [comment]
That rendering issue is fixed. Was cause when horizontally scrolling and I incorrectly calculated the first partial indent.

As for those scopes, you probably changed the text object settings? Can you please remove all the settings you have regarding that and try again?

You're probably using indent based scopes for text objects, but it's much better to use the treesitter scopes instead.
Just use the default config for textobjects,

**Comment by kiyoon** [comment]
I updated snacks (commit 188b043) and I still see the rendering issue.

Also I removed the settings and it is still like that.

```lua
  {
    -- Alternative to indent-blankline and treesitter-indent-object
    "folke/snacks.nvim",
    opts = {
      indent = {
        -- your indent configuration comes here
        -- or leave it empty to use the default settings
        -- refer to the configuration section below
        indent = {
          only_scope = true, -- only show indent guides of the scope
        },
        scope = {
          enabled = true,
          underline = true,
        },
        animate = {
          enabled = false,
        },
      },
      scope = {
        enabled = true,
        -- These keymaps will only be set if the `scope` plugin is enabled.
        -- Alternatively, you can set them manually in your config,
        -- using the `Snacks.scope.textobject` and `Snacks.scope.jump` functions.
      },
    },
  },
```

**Comment by folke** [comment]
I opened an issue. Seems the `only_Scope=true` is causing the issues

**Comment by kiyoon** [comment]
Thank for fixing the rendering issue. I think the only issue now is that in python `vai` selects one more line below than expected. My setting is just like above. Thanks!

**Comment by folke** [comment]
Can you post example code? It does not for me.

You do have the python treesitter installed right?
If not, it would use indent based scopes and would indeed select the bottom part as well.

Do `:TSInstall python`

**Comment by kiyoon** [comment]
1. Can the indent-based scope discard the bottom line in python as an exception? This would be more intuitive.
2. Could there be a fine-grained selection for `vii`? For example,

```python
if a:
    b
elif c:
    d
```

Current `vii` selects line 2-4, but would it be possible to select only one (if or elseif) block?

**Comment by kiyoon** [comment]
(Right now I'm using the treesitter based algorithm)

https://github.com/user-attachments/assets/7ddf1343-88d6-4b4c-9055-059e6e09a239

4. `vai` sometimes select different from what is shown as snack.indent. Can this be synchronised?

**Comment by pBorak** [comment]
For Ruby, I observe the same behavior with if/else as described above for Python. The `vii` selects both if and else.
Other than that everything works great for me

**Comment by folke** [comment]
@pBorak with treesitter parser?

**Comment by pBorak** [comment]
@folke Yes sorry, should have mentioned it - I have treesitter parser enabled 

```
require("nvim-treesitter.configs").setup({
  highlight = {
    enable = true,
  },
    indent = {
    enable = true,
  }
})
```

```
  {
    'folke/snacks.nvim',
    priority = 1000,
    lazy = false,
    opts = {
      bigfile = { enabled = true },
      notifier = {
        enabled = true,
        timeout = 3000,
      },
      scope = { enabled = true },
      indent = { enabled = true },
 ...
  }
  ```

**Comment by folke** [comment]
treesitter scopes are now also enabled if you disabled treesitter highlighting

**Comment by kiyoon** [comment]
@folke Thank you!
