### ISSUE TITLE
bug: Snacks.scroll + Snacks.words cursor ends up at wrong place

### ISSUE THREAD

**Issue by sudo-tee** [folke/snacks.nvim#236]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1328+g4889935a7a

### Operating system/version

WSL

### Describe the bug

When using a mix of scrolling and jumping to next reference the cursor will end up at the start of the line instead of the next occurence of the word/reference.

[scroll+words.webm](https://github.com/user-attachments/assets/cd4075b9-c315-43a4-a4ec-fb003196c9cd)

### Steps To Reproduce

- Open a file long enough to have scrolling
- Press the keymap for next ref ]] until a scroll happens
- whatch the cursor being positioned at the start of the line instead of the word itself

### Expected Behavior

cursor should be placed on the occurence of the word

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts =  {
  'folke/snacks.nvim',
  event = 'VeryLazy',
  keys = {
    {
      '<leader>up',
      function()
        require('snacks.profiler').toggle()
      end,
    },
    {
      '<leader>uP',
      function()
        require('snacks.profiler').scratch()
      end,
      desc = 'Profiler Scratch Bufer',
    },
    {
      ']]',
      desc = 'Next Reference',
      function()
        Snacks.words.jump(vim.v.count1)
      end,
    },
    {
      '[[',
      desc = 'Prev Reference',
      function()
        Snacks.words.jump(-vim.v.count1)
      end,
    },
  },
  ---@type snacks.Config
  opts = {
    bigfile = { enabled = true },
    quickfile = { enabled = true },
    styles = {
      notification = {
        wo = { wrap = true },
      },
    },
    notifier = {
      enabled = true,
    },
    words = {
      enabled = true,
    },
    scroll = {
      enabled = true,
    },
  },
} },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Yeah, I see that too. It also happens when you search for a word with `/pattern` and then press `n` to go to next search item. If it has to scroll then it positions the cursor at the start of the line indeed.

**Comment by folke** [comment]
Should be fixed now. Let me know if you are still seeing this!

**Comment by dpetka2001** [comment]
Seems to be working correctly now.

**Comment by sudo-tee** [comment]
Wow that was fast... 
It works properly now :)

**Comment by dpetka2001** [comment]
@folke One more thing I should mention is that there are also problems when you are in diff mode. I use `diffview.nvim` and when I do for example `DiffviewFileHistory %` and then press `]c`/`[c` to go to next/previous diff change it also doesn't work correctly. For now I just have a toggle mapping to disable when I'm in diff mode.

I don't know if this is in scope or not. I'm just mentioning it to let you know and you decide if something should be done or not.

**Comment by folke** [comment]
@dpetka2001 can you find a file in LAzyVim repo that exhibits this behavior so I can test?
With the files I tried it seemed to work as it should.

**Comment by dpetka2001** [comment]
I tried with the file `scroll.lua` of `snacks.nvim` repo. Let me try with a fresh LazyVim installation just in case and I'll get back to you.

**Comment by folke** [comment]
I just fixed an issue with scrollbind that might've been the cause. so update snacks

**Comment by dpetka2001** [comment]
I updated but still the same. Here's a screencast with fresh LazyVim installation

[Screencast_2024-12-10-21-48-42.webm](https://github.com/user-attachments/assets/e8c7e21c-220f-4dd7-bb23-86155ce72b8c)

**Comment by folke** [comment]
Small update: I'm still struggling with diff mode.
The problem is that specifically diff mode has a special `view` field `topfill`, that no other window has and I'm pretty sure that's what's causing issues.

I'm looking into a different way of doing the smooth scrolling and worst case will disable scroll in diff mode, till I find a better solution.

**Comment by dpetka2001** [comment]
No problem at all. If you end up disabling it that's totally good. That's what I'm doing now as well. If a proper solution is not possible, then disabling it in diff mode is the sane default.

**Comment by dpetka2001** [comment]
Hope I didn't put too much on your plate with this report. Sorry if I did.

**Comment by folke** [comment]
not at all! Found the actual issue is folds. Diff view has most code folded and I animate over all lines, including closed folds.

**Comment by YaroSpace** [comment]
> Yeah, I see that too. It also happens when you search for a word with `/pattern` and then press `n` to go to next search item. If it has to scroll then it positions the cursor at the start of the line indeed.

I am still experiencing the issue with search.  In my case, when I press `n` it jumps to the end of the file.  Words snack is disabled.

**Comment by dpetka2001** [comment]
After the last update I no longer experience the issue either with `snacks.words` or when searching with `/pattern`. Did you update to latest `snacks.nvim` version?

**Comment by YaroSpace** [comment]
I did.

**Comment by folke** [comment]
Please update. Just pushed a bunch of changes. Should all be fixed now.

Do let me know if you'd still have issues.

**Comment by dpetka2001** [comment]
Everything seems to be working as expected with latest update. Tnx!! :smile:
