### ISSUE TITLE
bug: `input` does not execute parts of the `on_input` callback

### ISSUE THREAD

**Issue by chrisgrieser** [folke/snacks.nvim#257]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

macOS 15.1 (arm)

### Describe the bug

When using `input`, the callback is not executed correctly/fully. I am not 100% what the conditions are, but I think buffer changes during the callback are blocked.

This behavior does not happen when using nvim's default `vim.ui.input` or when using `dressing.nvim`'s input.

### Steps To Reproduce

1. Save this code as file:
```lua
---@diagnostic disable-next-line: missing-fields
vim.ui.input({ prompt = "Input: " }, function(input)
	if not input then return end
	local curPath = vim.fs.dirname(vim.api.nvim_buf_get_name(0))
	local newFile = curPath .. ("/%s.lua"):format(input) 
	vim.cmd.edit(newFile)
	vim.cmd.write(newFile)
end)
```

2. run it via `:source %`

Result: `newFile` is correctly created (`cmd.write`), but the buffer does not switch to it, meaning the `cmd.edit` part is blocked/ignored.

### Expected Behavior

The callback should be executed correctly. 

### Repro

```lua
local spec = {
	{
		"folke/snacks.nvim",
		opts = {
			input = { enabled = true },
		},
	},
}

--------------------------------------------------------------------------------
vim.env.LAZY_STDPATH = "/tmp/nvim-repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro { spec = spec }
```

**Comment by folke** [comment]
Right, didn't think of that.
Reason was that the input floating win is still the current window.
Either way, should be fixed now.

**Comment by chrisgrieser** [comment]
Thanks for the quick response as usual!

However, the update does not seem to fix the problem. Now when trying pressing enter in the confirm window, there is this error:

```
E5108: Error executing lua: .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:82: E565: Not allowed to change text or change window
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:82: in function 'confirm'
	.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:111: in function <.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:110>
	...er/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:227: in function <...er/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:224>
```

**Comment by folke** [comment]
Please try again. just pushed an update

**Comment by folke** [comment]
Right, it's `input` that is doing that in an `expr` keymap :)
Either way, should be fixed

**Comment by folke** [comment]
Weirdly enough, I didn't get that error...

**Comment by chrisgrieser** [comment]
yep, working fine now. Thank you!
