### ISSUE TITLE
bug: snacks.picker.grep does not highlight matches with ".*" regex

### ISSUE THREAD

**Issue by xzbdmw** [folke/snacks.nvim#878]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macos 14.2

### Describe the bug

Please see the video, the preview window get correct highlight, but result list doesn't.

https://github.com/user-attachments/assets/eefa6ce1-4db2-4828-8176-74b670e77028

### Steps To Reproduce

see video

### Expected Behavior

result list should get match highlight (red)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by xzbdmw** [comment]
@folke The new commit adds an extra match for a space:

<img width="1622" alt="Image" src="https://github.com/user-attachments/assets/6ab43df0-2c1b-4fee-a454-bdc1e2e46ff3" />

This don't work for glob patterns (previewer loses match too):

<img width="1622" alt="Image" src="https://github.com/user-attachments/assets/247f4195-f465-4fb6-87dd-bd738b8662a3" />

**Comment by folke** [comment]
fixed

**Comment by MayDomine** [comment]
It seems still broken when I pass --iglob argument.

<img width="1354" alt="Image" src="https://github.com/user-attachments/assets/4d658b58-f4e2-460d-bc84-a85438d59289" />
I have already update the latest version of snacks.nvim
