### ISSUE TITLE
bug: explorer doesn't open anymore on startup

### ISSUE THREAD

**Issue by segersniels** [folke/snacks.nvim#997]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.4

### Operating system/version

MacOS 15.2

### Describe the bug

When opening Neovim the explorer no longer automatically opens up.

### Steps To Reproduce

1. `nvim ~/.config/nvim`

### Expected Behavior

It used to pop up the explorer by default but now we have to `<leader>e` to open it up.

**Comment by folke** [comment]
Can't reproduce. Is explorer enabled? And you are not lazy-loading snacks?
What's your config?

**Comment by segersniels** [comment]
> Can't reproduce. Is explorer enabled? And you are not lazy-loading snacks?
> What's your config?

I'll check when I'm behind my computer. I have the explorer and picker extras enabled in LazyVim with barely anything configured on top. It used to work normally until I updated my plugins last night.

**Comment by segersniels** [comment]
@folke even when forcing to LazyVim version 8 and removing my entire snacks config it still doesn't open the explorer when I open neovim.

**Comment by segersniels** [comment]
```
snacks: require("snacks.health").check()

Snacks ~
- OK setup called

Snacks.bigfile ~
- OK setup {enabled}

Snacks.dashboard ~
- OK setup {enabled}
- OK setup ran
- WARNING dashboard did not open: `buffer has a name`

Snacks.explorer ~
- OK setup {enabled}

Snacks.input ~
- OK setup {enabled}
- OK `vim.ui.input` is set to `Snacks.input`

Snacks.lazygit ~
- ERROR {lazygit} not installed

Snacks.notifier ~
- OK setup {enabled}
- OK is ready

Snacks.picker ~
- OK setup {enabled}
- OK `vim.ui.select` is set to `Snacks.picker.select`
- OK Treesitter language `regex` is available
- OK 'git' `git version 2.47.0`
- OK 'rg' `ripgrep 14.1.1`
- OK `Snacks.picker.grep()` is available
- OK 'fd' `fd 10.2.0`
- OK `Snacks.picker.files()` is available
- OK `Snacks.picker.explorer()` is available
- OK `SQLite3` is available

Snacks.quickfile ~
- OK setup {enabled}

Snacks.scope ~
- OK setup {enabled}

Snacks.scroll ~
- OK setup {enabled}

Snacks.statuscolumn ~
- WARNING setup {disabled}
- OK is manually configured
  - `vim.o.statuscolumn = "%!v:lua.require'snacks.statuscolumn'.get()"`

Snacks.terminal ~
- OK shell configured
  - `vim.o.shell`: /bin/zsh
  - `parsed`: { "/bin/zsh" }

Snacks.toggle ~
- OK {which-key} is installed

Snacks.words ~
- OK setup {enabled}
````

**Comment by folke** [comment]
Can't reproduce. If you can create a repro using the template from the new issue page, I can look at it.

**Comment by segersniels** [comment]
> Can't reproduce. If you can create a repro using the template from the new issue page, I can look at it.

Ok so I built up my config from scratch one by one and pinned it down to this exact plugin causing issues:

```lua
return {
	{
		"rmagatti/auto-session",
		lazy = false,
		opts = {
			enabled = true,
			auto_save = true,
			suppressed_dirs = { "~/", "~/projects", "~/personal", "~/Downloads", "/" },
		},
	},
}
```

If I enable auto session it doesn't open the explorer.

**Comment by folke** [comment]
Did you set the correct priority for snacks like instructed in the docs?

If that's the case, then it's probably auto-session that clears existing buffers to load a session?

Either way, this is probably somrting that should be fixed in auto-session

**Comment by segersniels** [comment]
> Did you set the correct priority for snacks like instructed in the docs?
> 
> If that's the case, then it's probably auto-session that clears existing buffers to load a session?
> 
> Either way, this is probably somrting that should be fixed in auto-session

I tried adding `priority = 1000` manually (using LazyVim explorer and picker extras) in my snacks config and it still happens. So that doesn't seem like the issue. Might be an auto-session issue then.
